package com.adbcontrol.companion.core

import android.Manifest

object AndroidCapabilityCatalog {
    fun defaultCapabilities(): List<CompanionCapability> = listOf(
        CompanionCapability(
            id = "android.input.ime",
            title = "Input method and text injection",
            androidPermissions = emptyList(),
            specialGrants = listOf("input-method-service"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("input.text", "input.key"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.screen.capture",
            title = "Screen capture and casting",
            androidPermissions = listOf(
                Manifest.permission.FOREGROUND_SERVICE,
                Manifest.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION,
            ),
            specialGrants = listOf("media-projection-consent"),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("stream.open", "stream.close", "screenshot.capture"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.file.read",
            title = "File read",
            androidPermissions = listOf(
                Manifest.permission.READ_MEDIA_IMAGES,
                Manifest.permission.READ_MEDIA_VIDEO,
                Manifest.permission.READ_MEDIA_AUDIO,
            ),
            specialGrants = listOf("scoped-storage-or-document-picker"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("file.read"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.file.write",
            title = "File write",
            androidPermissions = emptyList(),
            specialGrants = listOf("scoped-storage-or-document-picker"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("file.write"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.camera.stream",
            title = "Camera stream",
            androidPermissions = listOf(Manifest.permission.CAMERA),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("camera.open", "camera.close"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.audio.record",
            title = "Audio recording",
            androidPermissions = listOf(Manifest.permission.RECORD_AUDIO),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("audio.record.start", "audio.record.stop"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.sms.read",
            title = "SMS read",
            androidPermissions = listOf(Manifest.permission.READ_SMS),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("sms.read"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.sms.send",
            title = "SMS send",
            androidPermissions = listOf(Manifest.permission.SEND_SMS),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("sms.send"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.phone.call",
            title = "Phone call",
            androidPermissions = listOf(Manifest.permission.CALL_PHONE, Manifest.permission.READ_PHONE_STATE),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("phone.call"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.clipboard.read",
            title = "Clipboard read",
            androidPermissions = emptyList(),
            specialGrants = listOf("foreground-required"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("clipboard.read"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.clipboard.write",
            title = "Clipboard write",
            androidPermissions = emptyList(),
            specialGrants = listOf("sensitive-clip-flag"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("clipboard.write"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.sensor.motion",
            title = "Motion and orientation sensors",
            androidPermissions = emptyList(),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.MEDIUM,
            operations = listOf("sensor.subscribe", "sensor.unsubscribe"),
            requiresUserConsent = false,
        ),
        CompanionCapability(
            id = "android.app.list",
            title = "Application list",
            androidPermissions = emptyList(),
            specialGrants = listOf("package-visibility-query"),
            sensitivity = CapabilitySensitivity.MEDIUM,
            operations = listOf("app.list"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.volume.media",
            title = "Media volume control",
            androidPermissions = emptyList(),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.MEDIUM,
            operations = listOf("volume.get", "volume.set"),
            requiresUserConsent = false,
        ),
        CompanionCapability(
            id = "android.ui.background_surface",
            title = "Background surface prompt",
            androidPermissions = emptyList(),
            specialGrants = listOf("background-launch-policy"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("ui.surface.show"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.ui.overlay",
            title = "Overlay window",
            androidPermissions = listOf(Manifest.permission.SYSTEM_ALERT_WINDOW),
            specialGrants = listOf("draw-over-apps"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("overlay.show", "overlay.hide"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.intent.chain_launch",
            title = "Chained intent launch",
            androidPermissions = emptyList(),
            specialGrants = listOf("explicit-intent-only"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("intent.chainLaunch"),
            requiresUserConsent = true,
        ),
    )
}
