package com.adbcontrol.companion.core

import android.Manifest

object AndroidCapabilityCatalog {
    fun defaultCapabilities(): List<CompanionCapability> = listOf(
        CompanionCapability(
            id = "android.input.ime",
            title = "输入法与文本注入",
            androidPermissions = emptyList(),
            specialGrants = listOf("input-method-service"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("input.text", "input.key"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.screen.capture",
            title = "屏幕采集与投屏",
            androidPermissions = listOf(
                Manifest.permission.FOREGROUND_SERVICE,
                Manifest.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION,
            ),
            specialGrants = listOf("media-projection-consent"),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("stream.open", "stream.close", "screenshot.capture"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.file.read",
            title = "文件读取",
            androidPermissions = listOf(
                Manifest.permission.READ_MEDIA_IMAGES,
                Manifest.permission.READ_MEDIA_VIDEO,
                Manifest.permission.READ_MEDIA_AUDIO,
            ),
            specialGrants = listOf("scoped-storage-or-document-picker"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("file.read"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.file.write",
            title = "文件写入",
            androidPermissions = emptyList(),
            specialGrants = listOf("scoped-storage-or-document-picker"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("file.write"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.camera.stream",
            title = "相机画面",
            androidPermissions = listOf(Manifest.permission.CAMERA),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("camera.open", "camera.close"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.audio.record",
            title = "音频录制",
            androidPermissions = listOf(Manifest.permission.RECORD_AUDIO),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("audio.record.start", "audio.record.stop"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.sms.read",
            title = "短信读取",
            androidPermissions = listOf(Manifest.permission.READ_SMS),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("sms.read"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.sms.send",
            title = "短信发送",
            androidPermissions = listOf(Manifest.permission.SEND_SMS),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("sms.send"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.phone.call",
            title = "电话拨号",
            androidPermissions = listOf(Manifest.permission.CALL_PHONE, Manifest.permission.READ_PHONE_STATE),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.CRITICAL,
            operations = listOf("phone.call"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.clipboard.read",
            title = "剪贴板读取",
            androidPermissions = emptyList(),
            specialGrants = listOf("foreground-required"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("clipboard.read"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.clipboard.write",
            title = "剪贴板写入",
            androidPermissions = emptyList(),
            specialGrants = listOf("sensitive-clip-flag"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("clipboard.write"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.sensor.motion",
            title = "运动与方向传感器",
            androidPermissions = emptyList(),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.MEDIUM,
            operations = listOf("sensor.subscribe", "sensor.unsubscribe"),
            requiresUserConsent = false,
        ),
        CompanionCapability(
            id = "android.app.list",
            title = "应用列表",
            androidPermissions = emptyList(),
            specialGrants = listOf("package-visibility-query"),
            sensitivity = CapabilitySensitivity.MEDIUM,
            operations = listOf("app.list"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.volume.media",
            title = "媒体音量控制",
            androidPermissions = emptyList(),
            specialGrants = emptyList(),
            sensitivity = CapabilitySensitivity.MEDIUM,
            operations = listOf("volume.get", "volume.set"),
            requiresUserConsent = false,
        ),
        CompanionCapability(
            id = "android.ui.background_surface",
            title = "后台界面唤起",
            androidPermissions = emptyList(),
            specialGrants = listOf("background-launch-policy"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("ui.surface.show"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.ui.overlay",
            title = "悬浮窗",
            androidPermissions = listOf(Manifest.permission.SYSTEM_ALERT_WINDOW),
            specialGrants = listOf("draw-over-apps"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("overlay.show", "overlay.hide"),
            requiresUserConsent = true,
        ),
        CompanionCapability(
            id = "android.intent.chain_launch",
            title = "链式 Intent 启动",
            androidPermissions = emptyList(),
            specialGrants = listOf("explicit-intent-only"),
            sensitivity = CapabilitySensitivity.HIGH,
            operations = listOf("intent.chainLaunch"),
            requiresUserConsent = true,
        ),
    )
}
